-- MySQL Script generated by MySQL Workbench
-- 05/31/17 22:36:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema portal_znanja
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema portal_znanja
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `portal_znanja` DEFAULT CHARACTER SET utf8 ;
USE `portal_znanja` ;

-- -----------------------------------------------------
-- Table `portal_znanja`.`drzava`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_znanja`.`drzava` (
  `id_drzava` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_drzava`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_znanja`.`korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_znanja`.`korisnik` (
  `id_korisnik` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `prezime` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `lozinka` VARCHAR(45) NOT NULL,
  `korisnicko_ime` VARCHAR(45) NOT NULL,
  `uloga` ENUM('korisnik', 'djelatnik') NOT NULL,
  `tip` VARCHAR(45) NOT NULL,
  `drzava_id_drzava` INT NOT NULL,
  PRIMARY KEY (`id_korisnik`, `drzava_id_drzava`),
  UNIQUE INDEX `e-mail_UNIQUE` (`email` ASC),
  UNIQUE INDEX `korisnicko_ime_UNIQUE` (`korisnicko_ime` ASC),
  INDEX `fk_korisnik_drzava1_idx` (`drzava_id_drzava` ASC),
  CONSTRAINT `fk_korisnik_drzava1`
    FOREIGN KEY (`drzava_id_drzava`)
    REFERENCES `portal_znanja`.`drzava` (`id_drzava`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_znanja`.`predmeti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_znanja`.`predmeti` (
  `id_predmeta` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_predmeta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_znanja`.`literatura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_znanja`.`literatura` (
  `id_literatura` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  `id_predmeta` INT NOT NULL,
  `slika` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_literatura`, `id_predmeta`),
  INDEX `fk_literatura_predmeti1_idx` (`id_predmeta` ASC),
  CONSTRAINT `fk_literatura_predmeti1`
    FOREIGN KEY (`id_predmeta`)
    REFERENCES `portal_znanja`.`predmeti` (`id_predmeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_znanja`.`zadaci`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_znanja`.`zadaci` (
  `id_zadaci` INT NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(45) NOT NULL,
  `id_predmeta` INT NOT NULL,
  `slika` VARCHAR(45) NULL,
  PRIMARY KEY (`id_zadaci`, `id_predmeta`),
  INDEX `fk_zadaci_predmeti1_idx` (`id_predmeta` ASC),
  CONSTRAINT `fk_zadaci_predmeti1`
    FOREIGN KEY (`id_predmeta`)
    REFERENCES `portal_znanja`.`predmeti` (`id_predmeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_znanja`.`blog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_znanja`.`blog` (
  `id_blog` INT NOT NULL AUTO_INCREMENT,
  `komentari` VARCHAR(400) NOT NULL,
  `korisnik_id_korisnik` INT NOT NULL,
  PRIMARY KEY (`id_blog`, `korisnik_id_korisnik`),
  INDEX `fk_blog_korisnik1_idx` (`korisnik_id_korisnik` ASC),
  CONSTRAINT `fk_blog_korisnik1`
    FOREIGN KEY (`korisnik_id_korisnik`)
    REFERENCES `portal_znanja`.`korisnik` (`id_korisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `portal_znanja`.`korisnik_has_predmeti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `portal_znanja`.`korisnik_has_predmeti` (
  `korisnik_id_korisnik` INT NOT NULL,
  `predmeti_id_predmeta` INT NOT NULL,
  PRIMARY KEY (`korisnik_id_korisnik`, `predmeti_id_predmeta`),
  INDEX `fk_korisnik_has_predmeti_predmeti1_idx` (`predmeti_id_predmeta` ASC),
  INDEX `fk_korisnik_has_predmeti_korisnik1_idx` (`korisnik_id_korisnik` ASC),
  CONSTRAINT `fk_korisnik_has_predmeti_korisnik1`
    FOREIGN KEY (`korisnik_id_korisnik`)
    REFERENCES `portal_znanja`.`korisnik` (`id_korisnik`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_korisnik_has_predmeti_predmeti1`
    FOREIGN KEY (`predmeti_id_predmeta`)
    REFERENCES `portal_znanja`.`predmeti` (`id_predmeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
